/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dee9fc",
        "tertiary-container": "#006848",
        "surface-bright": "#f8f9ff",
        "secondary": "#006a6a",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "on-primary-container": "#c4d2ff",
        "on-surface": "#121c2a",
        "on-primary-fixed": "#001848",
        "tertiary-fixed-dim": "#45dfa4",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#002020",
        "secondary-fixed-dim": "#76d6d5",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6d6",
        "on-primary": "#ffffff",
        "on-secondary-container": "#006e6e",
        "surface-variant": "#d9e3f6",
        "primary-fixed-dim": "#b2c5ff",
        "on-error": "#ffffff",
        "tertiary": "#004e34",
        "on-background": "#121c2a",
        "surface-container-low": "#eff4ff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#434654",
        "surface-tint": "#0c56d0",
        "outline": "#737685",
        "secondary-fixed": "#93f2f2",
        "primary-fixed": "#dae2ff",
        "on-primary-fixed-variant": "#0040a2",
        "error-container": "#ffdad6",
        "surface-dim": "#d0dbed",
        "on-tertiary-fixed-variant": "#005137",
        "primary": "#003d9b",
        "tertiary-fixed": "#68fcbf",
        "secondary-container": "#90efef",
        "on-tertiary-container": "#55ecb0",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#002114",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d9e3f6",
        "primary-container": "#0052cc",
        "inverse-surface": "#27313f",
        "surface-container": "#e6eeff",
        "on-secondary-fixed-variant": "#004f4f",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-md": "16px",
        "container-max": "1200px",
        "unit": "8px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-lg": ["Google Sans", "Inter", "Sarabun"],
        "label-md": ["Google Sans", "Inter", "Sarabun"],
        "headline-lg-mobile": ["Google Sans", "Inter", "Sarabun"],
        "body-md": ["Google Sans", "Inter", "Sarabun"],
        "label-sm": ["Google Sans", "Inter", "Sarabun"],
        "display-lg": ["Google Sans", "Inter", "Sarabun"],
        "headline-md": ["Google Sans", "Inter", "Sarabun"],
        "body-lg": ["Google Sans", "Inter", "Sarabun"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
